import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LandingWeb</Link>
        </li>
        <li>
          <Link to="/registerweb">RegisterWeb</Link>
        </li>
        <li>
          <Link to="/helpwebnonlogin">HelpWebNonLogin</Link>
        </li>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
        <li>
          <Link to="/mainweb">MainWeb</Link>
        </li>
        <li>
          <Link to="/mapweb">MapWeb</Link>
        </li>
        <li>
          <Link to="/settingsweb">SettingsWeb</Link>
        </li>
        <li>
          <Link to="/helpweb">HelpWeb</Link>
        </li>
        <li>
          <Link to="/profileweb">ProfileWeb</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
